### ISSUE TITLE
Unique usernames

### ISSUE THREAD

**Issue by Cborek** [thawkin3/chat-sockets#13]
I've noticed that users can have the same usernames without issue. I'd suggest limiting/preventing this.

**Comment by thawkin3** [comment]
@Cborek Good suggestion. I originally let the usernames be non-unique on purpose, but it could be good to enforce uniqueness. One of the problems is that the app isn't actually hooked up to a database, it just keeps up to 50 comments in memory on the server, so when you join the chatroom you don't actually get entered into a database of users. So I think I'd be able to enforce uniqueness for users that are currently in the chatroom, but since there's no database or authentication or login I probably wouldn't be able to enforce uniqueness across time.

So for example, you could have a Colin user in the chatroom, and we could prevent another Colin from joining the chatroom while you were online, but then once you leave the chatroom we'd have no way of knowing if the next Colin that tries to join the chatroom is really you or is a different user.

But for this app maybe that's not important to maintain uniqueness across time. Just preventing concurrent users from having the same username could be good.

Does that work?

**Comment by Cborek** [comment]
@thawkin3 I think that just enforcing across users that are currently in the chatroom is probably fine in terms of this application. I don't think it's very necessary to maintain over time either.

**Comment by thawkin3** [comment]
@Cborek Awesome, I'll move forward with that idea then. I'll let you know once it's implemented. Thanks for the input!

**Comment by thawkin3** [comment]
@Cborek Ok this should be implemented now. Thanks for the thoughtful input!
